# SPDX-FileCopyrightText: The RamenDr authors
# SPDX-License-Identifier: Apache-2.0

---
name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spell:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: go.sum

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  build-matrix:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create build tag
        run: git tag build-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Download modules
        run: go mod download
      - name: Build binary
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ramenctl-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ramenctl*
          retention-days: 15
          compression-level: 9

  test-matrix:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        # See https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        runner:
          - ubuntu-24.04 # x86_64
          - ubuntu-24.04-arm # arm64
          - windows-latest # x86_64
          - macos-13 # x86_64
          - macos-15 # arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create build tag
        run: git tag latest
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Download modules
        run: go mod download
      - name: Setup go env
        # https://github.com/golang/go/issues/75031
        run: go env -w GOTOOLCHAIN=go1.25.0+auto
      - name: Run tests
        run: make test
